### PR TITLE
Adding code of conduct to reference knative/community's CoC

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by rhuss** [comment]
@dprotaso @evankanderson could I please get a lgtm for this PR ?

btw, do we still need this repo ?

**Comment by dprotaso** [comment]
Do we even need this repo anymore?

**Comment by evankanderson** [comment]
I think we can archive or even delete. I think this was an early version of functions.

**Comment by dprotaso** [comment]
Done here: https://github.com/knative/community/pull/1020

I'll close out PRs

**Pull request closed without merging**
